echo ""
echo "=========================="
echo "== Free-threaded Python =="
echo "=========================="
echo ""
echo "Welcome to the Experimental Free-Threaded Python."
echo ""
echo "This environment is experimental and designed for testing and exploratory purposes."
echo "Here you can investigate the behavior and performance of Python in a free-threaded context."
echo ""
echo "It is NOT production-ready."
echo ""
echo "Your experiences and insights are invaluable in helping us improve this environment."
echo -e "Please report any bugs, issues, or suggestions via our \e]8;;https://github.com/NVIDIA/free-threaded-python/issues\aGitHub Issues\e]8;;\a."
echo ""
